### Register user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "test255",
  "password": "1234"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "test255",
  "password": "1234"
}

### Use JWT for /me
GET http://localhost:5000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2NTQ0NjkzMSwianRpIjoiYTdjODM2NDItOGQyNC00NzY1LWI1NzUtYjgwOWUyNzcyMmU5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NjU0NDY5MzEsImV4cCI6MTc2NTQ0NzgzMX0.0E1N43vzKFgvHG8URkkMy2dLQZpI-xOaFZ32j6pKsTA

### Add a book
POST http://localhost:5000/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "title": "Flask Senior Guide",
  "author": "mee"
}

### Get all books
GET http://localhost:5000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Cache expensive
GET http://localhost:5000/cache/expensive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Clear cache
POST http://localhost:5000/cache/clear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
