### Register user
POST https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/auth/register
Content-Type: application/json

{
  "username": "test8",
  "password": "1234"
}

### Login to get JWT
POST https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

> {% client.global.set("jwt_token", response.body.access_token) %}

### Use JWT for /me
GET https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/auth/me
Authorization: Bearer {{jwt_token}}

### Add a book
POST https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/api/books
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Flask Senior Guide",
  "author": "mee"
}

### Get all books
GET https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/api/books
Authorization: Bearer {{jwt_token}}

### Cache expensive
GET https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/cache/expensive
Authorization: Bearer {{jwt_token}}

### Clear cache
GET https://probable-bassoon-4v54qrpq9rq2wvx-80.app.github.dev/cache/clear
Authorization: Bearer {{jwt_token}}
